name: neoPaintingSwitch
main: plugin.arcwolf.neopaintingswitch.neoPaintingSwitch
version: 1.31
permissions:
    neopaintingswitch.*:
        description: Wildcard option for comfort.
        children:
            neopaintingswitch.use: true
    neopaintingswitch.use:
        description: Allows the user to scroll through paintings.
        default: op